image: java:8-jdk

stages:
  - build
  - deploy

assemble:
  stage: build
  script:
    - ./gradlew assembleDist

server:
  stage: build
  script:
    - ./gradlew assembleUnixDist
    - cd docker
    - docker build -t nbt-mm:latest --build-arg tarballName=megamek-0.45.3-SNAPSHOT .
