image: docker:latest

services:
  - docker:dind

variables:
  - AWS_ECR_URI: 068936280303.dkr.ecr.us-west-2.amazonaws.com/nbt-mm

stages:
  - build
  - deploy

assemble:
  image: gradle:jdk8
  stage: build
  script:
    - ./gradlew assembleDist

server:
  image: gradle:jdk8
  stage: build
  script:
    - ./gradlew assembleUnixDist
  artifacts:
    paths:
      - megamek/build/distributions/*

deploy_client:
  stage: deploy
  script: 
    - ls

deploy_server:
  stage: deploy
  script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region us-west-1)
    - cd docker
    - docker build -t $AWS_ECR_URI --build-arg tarballName=megamek-0.45.3-SNAPSHOT .
    - docker push $AWS_ECR_URI

